/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ControlTowerRouteImport } from './routes/control-tower'
import { Route as DecisionEconomicsRouteImport } from './routes/decision-economics'
import { Route as ExceptionsRouteImport } from './routes/exceptions'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ModelMonitorRouteImport } from './routes/model-monitor'
import { Route as NetworkMapRouteImport } from './routes/network-map'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResolutionHubRouteImport } from './routes/resolution-hub'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShipmentsRouteImport } from './routes/shipments'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as ApiLearningAuditRouteImport } from './routes/api/learning-audit'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiLearningSplatRouteImport } from './routes/api/learning/$'
import { Route as ApiOrcaSplatRouteImport } from './routes/api/orca/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlTowerRoute = ControlTowerRouteImport.update({
  id: '/control-tower',
  path: '/control-tower',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionEconomicsRoute = DecisionEconomicsRouteImport.update({
  id: '/decision-economics',
  path: '/decision-economics',
  getParentRoute: () => rootRouteImport,
} as any)
const ExceptionsRoute = ExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelMonitorRoute = ModelMonitorRouteImport.update({
  id: '/model-monitor',
  path: '/model-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkMapRoute = NetworkMapRouteImport.update({
  id: '/network-map',
  path: '/network-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResolutionHubRoute = ResolutionHubRouteImport.update({
  id: '/resolution-hub',
  path: '/resolution-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsRoute = ShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLearningAuditRoute = ApiLearningAuditRouteImport.update({
  id: '/api/learning-audit',
  path: '/api/learning-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLearningSplatRoute = ApiLearningSplatRouteImport.update({
  id: '/api/learning/$',
  path: '/api/learning/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrcaSplatRoute = ApiOrcaSplatRouteImport.update({
  id: '/api/orca/$',
  path: '/api/orca/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/control-tower': typeof ControlTowerRoute
  '/decision-economics': typeof DecisionEconomicsRoute
  '/exceptions': typeof ExceptionsRoute
  '/mcp': typeof McpRoute
  '/model-monitor': typeof ModelMonitorRoute
  '/network-map': typeof NetworkMapRoute
  '/reports': typeof ReportsRoute
  '/resolution-hub': typeof ResolutionHubRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRoute
  '/simulator': typeof SimulatorRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/learning-audit': typeof ApiLearningAuditRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/learning/$': typeof ApiLearningSplatRoute
  '/api/orca/$': typeof ApiOrcaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/control-tower': typeof ControlTowerRoute
  '/decision-economics': typeof DecisionEconomicsRoute
  '/exceptions': typeof ExceptionsRoute
  '/mcp': typeof McpRoute
  '/model-monitor': typeof ModelMonitorRoute
  '/network-map': typeof NetworkMapRoute
  '/reports': typeof ReportsRoute
  '/resolution-hub': typeof ResolutionHubRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRoute
  '/simulator': typeof SimulatorRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/learning-audit': typeof ApiLearningAuditRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/learning/$': typeof ApiLearningSplatRoute
  '/api/orca/$': typeof ApiOrcaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/control-tower': typeof ControlTowerRoute
  '/decision-economics': typeof DecisionEconomicsRoute
  '/exceptions': typeof ExceptionsRoute
  '/mcp': typeof McpRoute
  '/model-monitor': typeof ModelMonitorRoute
  '/network-map': typeof NetworkMapRoute
  '/reports': typeof ReportsRoute
  '/resolution-hub': typeof ResolutionHubRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRoute
  '/simulator': typeof SimulatorRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/learning-audit': typeof ApiLearningAuditRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/learning/$': typeof ApiLearningSplatRoute
  '/api/orca/$': typeof ApiOrcaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/control-tower'
    | '/decision-economics'
    | '/exceptions'
    | '/mcp'
    | '/model-monitor'
    | '/network-map'
    | '/reports'
    | '/resolution-hub'
    | '/settings'
    | '/shipments'
    | '/simulator'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/learning-audit'
    | '/.mcp/invoke-tool/$tool'
    | '/api/learning/$'
    | '/api/orca/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/control-tower'
    | '/decision-economics'
    | '/exceptions'
    | '/mcp'
    | '/model-monitor'
    | '/network-map'
    | '/reports'
    | '/resolution-hub'
    | '/settings'
    | '/shipments'
    | '/simulator'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/learning-audit'
    | '/.mcp/invoke-tool/$tool'
    | '/api/learning/$'
    | '/api/orca/$'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/control-tower'
    | '/decision-economics'
    | '/exceptions'
    | '/mcp'
    | '/model-monitor'
    | '/network-map'
    | '/reports'
    | '/resolution-hub'
    | '/settings'
    | '/shipments'
    | '/simulator'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/learning-audit'
    | '/.mcp/invoke-tool/$tool'
    | '/api/learning/$'
    | '/api/orca/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ControlTowerRoute: typeof ControlTowerRoute
  DecisionEconomicsRoute: typeof DecisionEconomicsRoute
  ExceptionsRoute: typeof ExceptionsRoute
  McpRoute: typeof McpRoute
  ModelMonitorRoute: typeof ModelMonitorRoute
  NetworkMapRoute: typeof NetworkMapRoute
  ReportsRoute: typeof ReportsRoute
  ResolutionHubRoute: typeof ResolutionHubRoute
  SettingsRoute: typeof SettingsRoute
  ShipmentsRoute: typeof ShipmentsRoute
  SimulatorRoute: typeof SimulatorRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiLearningAuditRoute: typeof ApiLearningAuditRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiLearningSplatRoute: typeof ApiLearningSplatRoute
  ApiOrcaSplatRoute: typeof ApiOrcaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-tower': {
      id: '/control-tower'
      path: '/control-tower'
      fullPath: '/control-tower'
      preLoaderRoute: typeof ControlTowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decision-economics': {
      id: '/decision-economics'
      path: '/decision-economics'
      fullPath: '/decision-economics'
      preLoaderRoute: typeof DecisionEconomicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exceptions': {
      id: '/exceptions'
      path: '/exceptions'
      fullPath: '/exceptions'
      preLoaderRoute: typeof ExceptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-monitor': {
      id: '/model-monitor'
      path: '/model-monitor'
      fullPath: '/model-monitor'
      preLoaderRoute: typeof ModelMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network-map': {
      id: '/network-map'
      path: '/network-map'
      fullPath: '/network-map'
      preLoaderRoute: typeof NetworkMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resolution-hub': {
      id: '/resolution-hub'
      path: '/resolution-hub'
      fullPath: '/resolution-hub'
      preLoaderRoute: typeof ResolutionHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments': {
      id: '/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof ShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning-audit': {
      id: '/api/learning-audit'
      path: '/api/learning-audit'
      fullPath: '/api/learning-audit'
      preLoaderRoute: typeof ApiLearningAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/$': {
      id: '/api/learning/$'
      path: '/api/learning/$'
      fullPath: '/api/learning/$'
      preLoaderRoute: typeof ApiLearningSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orca/$': {
      id: '/api/orca/$'
      path: '/api/orca/$'
      fullPath: '/api/orca/$'
      preLoaderRoute: typeof ApiOrcaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ControlTowerRoute: ControlTowerRoute,
  DecisionEconomicsRoute: DecisionEconomicsRoute,
  ExceptionsRoute: ExceptionsRoute,
  McpRoute: McpRoute,
  ModelMonitorRoute: ModelMonitorRoute,
  NetworkMapRoute: NetworkMapRoute,
  ReportsRoute: ReportsRoute,
  ResolutionHubRoute: ResolutionHubRoute,
  SettingsRoute: SettingsRoute,
  ShipmentsRoute: ShipmentsRoute,
  SimulatorRoute: SimulatorRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiLearningAuditRoute: ApiLearningAuditRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiLearningSplatRoute: ApiLearningSplatRoute,
  ApiOrcaSplatRoute: ApiOrcaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
