/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ControlTowerRouteImport } from './routes/control-tower'
import { Route as ApiOrcaSplatRouteImport } from './routes/api/orca/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlTowerRoute = ControlTowerRouteImport.update({
  id: '/control-tower',
  path: '/control-tower',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrcaSplatRoute = ApiOrcaSplatRouteImport.update({
  id: '/api/orca/$',
  path: '/api/orca/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/control-tower': typeof ControlTowerRoute
  '/api/orca/$': typeof ApiOrcaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/control-tower': typeof ControlTowerRoute
  '/api/orca/$': typeof ApiOrcaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/control-tower': typeof ControlTowerRoute
  '/api/orca/$': typeof ApiOrcaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/control-tower' | '/api/orca/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/control-tower' | '/api/orca/$'
  id: '__root__' | '/' | '/control-tower' | '/api/orca/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ControlTowerRoute: typeof ControlTowerRoute
  ApiOrcaSplatRoute: typeof ApiOrcaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-tower': {
      id: '/control-tower'
      path: '/control-tower'
      fullPath: '/control-tower'
      preLoaderRoute: typeof ControlTowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orca/$': {
      id: '/api/orca/$'
      path: '/api/orca/$'
      fullPath: '/api/orca/$'
      preLoaderRoute: typeof ApiOrcaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ControlTowerRoute: ControlTowerRoute,
  ApiOrcaSplatRoute: ApiOrcaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
